set(CPACK_PACKAGE_NAME "vacuo")
set(CPACK_PACKAGE_VENDOR "Trendorin")
set(CPACK_PACKAGE_CONTACT "https://github.com/Trendorin/Vacuo/issues")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Native, safety-first Linux cache cleaner")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/Trendorin/Vacuo")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_FILE_NAME "vacuo-${PROJECT_VERSION}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_PACKAGE_CHECKSUM SHA256)
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
set(CPACK_STRIP_FILES ON)

set(CPACK_GENERATOR "TGZ;DEB;RPM")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "vacuo-${PROJECT_VERSION}-source")
set(CPACK_SOURCE_IGNORE_FILES
    "/build/;/.git/;/.cache/;/.idea/;/.vscode/;~$;${CPACK_SOURCE_IGNORE_FILES}"
)

set(CPACK_DEBIAN_PACKAGE_NAME "vacuo")
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_DEBIAN_PACKAGE_SECTION "utils")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_PACKAGE_DEPENDS "policykit-1")

set(CPACK_RPM_PACKAGE_NAME "vacuo")
set(CPACK_RPM_FILE_NAME RPM-DEFAULT)
set(CPACK_RPM_PACKAGE_GROUP "Applications/System")
set(CPACK_RPM_PACKAGE_LICENSE "GPL-3.0-or-later")
set(CPACK_RPM_PACKAGE_REQUIRES "polkit")
set(CPACK_RPM_PACKAGE_AUTOREQ ON)

include(CPack)
